### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by agustingomes** [mezzio/mezzio-aurarouter#10]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Provide PHP 8.1 support. Once this is achieved, it should unblock https://github.com/mezzio/mezzio/issues/95

**Comment by froschdesign** [comment]
Related to https://github.com/auraphp/Aura.Router/pull/176

**Comment by weierophinney** [comment]
Related, as it may mean we can close this: #12

**Comment by froschdesign** [comment]
A [new version with support for PHP 8.1](https://github.com/auraphp/Aura.Router/releases/tag/3.2.0) has been released.

@agustingomes 
Would you be willing to create a pull request?

**Comment by agustingomes** [comment]
I can look into it tomorrow.

**Comment by agustingomes** [comment]
@froschdesign @weierophinney I opened a PR for it. I'm also dropping the support for 7.3 in the process since it's effectively EOL, but if support for it is still needed, I'll remove the type changes I've done in the PR and adjust the composer.json
