### ISSUE TITLE
[RFC]: Abandon this package

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-aurarouter#12]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | immediate |
| BC Break?           | No |

### Goal

I think we should just abandon this package. Aura Router has not had a release in almost 5 years, and no commits in over 3; it's effectively abandoned at this point. Without it getting updates, we cannot support PHP 8.0+ at this point. We've already made the decision not to list it in the skeleton installer; let's make it official that we won't continue development any longer.

**Comment by harikt** [comment]
Just a note : @koriym is trying to make a release for 4.x which supports 8.x version.  

So 8.x will continue to support. https://github.com/auraphp/Aura.Router/pull/177 .

Update : 3.x now supports 5.5 to 8.1.

**Comment by froschdesign** [comment]
A [new version with support for PHP 8.1](https://github.com/auraphp/Aura.Router/releases/tag/3.2.0) has been released.

**Comment by boesing** [comment]
Even tho, it now supports PHP 8.1, it seems that the aura router was not that popular (given the packagist installs):

![image](https://user-images.githubusercontent.com/2189546/152337217-9f56f2b1-238b-4499-a154-e3aec4f92393.png)
![image](https://user-images.githubusercontent.com/2189546/152337248-4cbb8591-415c-4842-b8d9-45b9eaa8cc03.png)
![image](https://user-images.githubusercontent.com/2189546/152337561-4719c9eb-a720-4b1f-a1aa-f9d1dd242076.png)

Since we do lack maintainers anyways, I'd suggest abandoning this component anyways. If there is a strong need for this component, one can still fork it and we can suggest that fork via `composer.json`.

**Comment by froschdesign** [comment]
@boesing 
The [previous version](https://github.com/auraphp/Aura.Router/releases/tag/3.1.0) was from 02 March 2017, this explains the statistics a little.

**Comment by boesing** [comment]
Not sure if thats something which is related.
The last version from Nikitas fastroute was from February 2018 and our glue-code (`mezzio-fastroute`) has ~26x more installs.

**Comment by boesing** [comment]
As I found this one related to the Psalm project in the Mezzio org, should we bring this up to the TSC?
I am still +1 on this. If someone has a need for it, this can be forked.

When comparing this component with the other routers available, I see that all other routers are even more used:

https://packagist.org/packages/mezzio/mezzio-laminasrouter/stats
https://packagist.org/packages/mezzio/mezzio-fastroute/stats
https://packagist.org/packages/mezzio/mezzio-aurarouter/stats

IMHO, we only need to support fastroute, as `laminas-router` has a lack of caching + speed. Even tho we have to support `laminas-router` as it is created from us PLUS used in `laminas-mvc`, I would not recommend using any other router than fastroute in a mezzio project. Maybe that symfony one as it seems to a little bit more performant than the fastroute router:

https://gist.github.com/azjezz/b2d09a6104b0bdfa4e00f3df96aadf7a

So in the end, I'd still support laminas-router as we kinda have to, but I'd definitely drop the aurarouter.

Thoughts?

**Comment by Ocramius** [comment]
Certainly no need to support it ourselves: can be forked and maintained further by others
